apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leatherman
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - "k8up.io"
  resources:
  - "*"
  verbs:
  - get
  - list